// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCptxOFRLJ6kQ8Te7r959y88rs3xlRz-X0',
    appId: '1:311604552227:web:eab018d81258ab5a9bc796',
    messagingSenderId: '311604552227',
    projectId: 'offerlite-d6977',
    authDomain: 'offerlite-d6977.firebaseapp.com',
    storageBucket: 'offerlite-d6977.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7UvUUjQb0j9kwX0D-ESg9VeQEeriUCe0',
    appId: '1:311604552227:android:395db3f3844f3e059bc796',
    messagingSenderId: '311604552227',
    projectId: 'offerlite-d6977',
    storageBucket: 'offerlite-d6977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvPmywo5NqXKEqPg_dcmRmKg8MXv_jsE',
    appId: '1:311604552227:ios:a3b1c31e20c1fc919bc796',
    messagingSenderId: '311604552227',
    projectId: 'offerlite-d6977',
    storageBucket: 'offerlite-d6977.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvPmywo5NqXKEqPg_dcmRmKg8MXv_jsE',
    appId: '1:311604552227:ios:a3b1c31e20c1fc919bc796',
    messagingSenderId: '311604552227',
    projectId: 'offerlite-d6977',
    storageBucket: 'offerlite-d6977.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCptxOFRLJ6kQ8Te7r959y88rs3xlRz-X0',
    appId: '1:311604552227:web:706622a0d073f1aa9bc796',
    messagingSenderId: '311604552227',
    projectId: 'offerlite-d6977',
    authDomain: 'offerlite-d6977.firebaseapp.com',
    storageBucket: 'offerlite-d6977.firebasestorage.app',
  );
}
